audit_header: false
title: Boston Real Estate Video Blog with Chris Remmes
description: >-
  Our mission at Coldwell Banker is to be your best resource for Boston real
  estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The Coldwell Banker, your professional
  Boston Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Chris Remmes
  title:
  license_number:
  about_markdown: >-
    As a longtime resident of Boston, Chris Remmes is recognized as one of the
    leading residential brokers in the Boston market. Chris brings a
    professional approach as well as a service-oriented philosophy to his real
    estate practice. He has built an excellent reputation and developed a loyal
    customer following of past clients and referrals by serving them well.


    Chris joined Hammond Residential after ten years in the real estate industry
    to provide his clients with the latest and most comprehensive marketing and
    cutting-edge technology available today. Hammond Residential was acquired by
    Coldwell Banker Residential Brokerage, which is renowned for its innovation
    and ingenuity and for leading the real estate industry with integrity and
    professionalism.


    As a graduate of Massachusetts Maritime Academy, Chris previously worked as
    a Deck Officer for Exxon where he sailed around the world and satisfied his
    passion for travel and adventure.&nbsp; At Exxon, his intuition and skills
    with technology established him as a leader.&nbsp; He was selected for
    special assignments, which developed technology solutions for the maritime
    industry.


    However, his love of Boston brought him back to his hometown. His career in
    real estate started in 1998 in the mortgage lending business. During this
    time, he obtained his MBA from Boston University.&nbsp; His knowledge of the
    real estate market and mortgage experience gives him a wide breadth of
    knowledge, which has helped him establish himself as a top broker in the
    Boston market. Chris works out of the Coldwell Banker offices in the South
    End and Charlestown; he is knowledgeable in all the downtown neighborhoods
    of Boston.
  market: Boston
  brand: Coldwell Banker
  brokerage:
  address: '105 Main St<br>Boston, MA 02129'
  phone: 617-398-0018
  phone_type:
  phone2:
  phone2_type:
  email: chris.remmes@nemoves.com
  url: 'http://chrisremmes.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.remmesre.com/sell/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.remmesre.com/map/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your Boston Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'http://www.remmesre.com/sell/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/006.jpg
    CTA_title2: Looking for a Boston Home?
    CTA_text2: Search the entire MLS for your Boston home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'http://www.remmesre.com/map/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: true
  facebook_url: 'https://www.facebook.com/ChrisRemmesRE/'
  linkedin_url: 'https://www.linkedin.com/in/chrisremmes/'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UCR77SvZYVatA5lpU2heFa4A'
  twitter_url: 'https://twitter.com/ChrisRemmesRE'
  instagram_url: 'https://www.instagram.com/chrisremmes/'
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Chris-Remmes/'
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Boston Real Estate Podcast with Chris Remmes
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Boston
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Coldwell Banker - your professional
    Boston Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Boston, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Chris Remmes
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: The Boston Real Estate Journal
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#092360'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'